plugin.yml: try using api-version 1.13
It somewhat works on 1.13.2, but not all functionality is available, for example
setting a sign fails with:

[11:29:25 WARN]: [WebSandboxMC] Task #199 for WebSandboxMC v2.0.0-SNAPSHOT generated an exception
java.lang.NoSuchFieldError: OAK_WALL_SIGN
	at io.github.satoshinm.WebSandboxMC.bridge.BlockBridge.clientNewSign(BlockBridge.java:1067) ~[?:?]
	at io.github.satoshinm.WebSandboxMC.ws.WebSocketServerThread.handle(WebSocketServerThread.java:261) ~[?:?]
	at io.github.satoshinm.WebSandboxMC.ws.WebSocketFrameHandler$1.run(WebSocketFrameHandler.java:70) ~[?:?]

because OAK_WALL_SIGN is not present in the API for 1.13.2, which was
added in 1.14. If we set api-version 1.17, then the plugin won't even load, however.