Revert "Refactor both Bukkit and Sponge configuration into the same class"
Sponge can load it just fine despite undefined references, but Bukkit cannot,
for some reason. Testing on Glowstone server:

17:20:20 [INFO] Scanning plugins...
17:20:20 [INFO] PluginTypeDetector: found 1 Bukkit, 1 Sponge, 0 Forge, 0 Canary, 0 unknown plugins (total 1)
17:20:20 [INFO] Set PluginClassLoader as parallel capable
17:20:20 [SEVERE] Could not load 'plugins/WebSandboxMC.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: ninja/leaping/configurate/loader/ConfigurationLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:339)
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255)
	at net.glowstone.GlowServer.loadPlugins(GlowServer.java:842)
	at net.glowstone.GlowServer.start(GlowServer.java:600)
	at net.glowstone.GlowServer.run(GlowServer.java:452)
	at net.glowstone.GlowServer.main(GlowServer.java:322)
Caused by: java.lang.NoClassDefFoundError: ninja/leaping/configurate/loader/ConfigurationLoader
	at io.github.satoshinm.WebSandboxMC.bukkit.WebSandboxPlugin.<init>(WebSandboxPlugin.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77)
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127)
	... 6 more
Caused by: java.lang.ClassNotFoundException: ninja.leaping.configurate.loader.ConfigurationLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
17:20:20 [WARNING] SpongeAPI plugins found, but no Sponge bridge present! They will be ignored.
17:20:20 [WARNING] Ignored SpongeAPI plugin: plugins/WebSandboxMC.jar
17:20:20 [WARNING] Suggestion: install https://github.com/deathcap/Bukkit2Sponge to load these plugins

This reverts commit be7a56f672b773ebf53cecac5d51263cac55543e.